MONGODB_HOST: mongodb-{{ env }}.daws86s.cfd
REDIS_HOST: redis-{{ env }}.daws86s.cfd
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.daws86s.cfd
CART_HOST: cart.backend-alb-{{ env }}.daws86s.cfd
MYSQL_HOST: mysql-{{ env }}.daws86s.cfd
RABBITMQ_HOST: rabbitmq-{{ env }}.daws86s.cfd
USER_HOST: user.backend-alb-{{ env }}.daws86s.cfd
SHIPPING_HOST: shipping.backend-alb-{{ env }}.daws86s.cfd
PAYMENT_HOST: payment.backend-alb-{{ env }}.daws86s.cfd